module UsersHelper

require 'crack' # XML and JSON parsingrequire 'crack/json' # Only JSON parsing
require 'crack/xml'
require 'time'
require 'uri'
require 'openssl'
require 'base64'

def search_items
  search_item = params[:search]
  # Your Access Key ID, as taken from the Your Account page

  # Your Secret Key corresponding to the above ID, as taken from the Your Account page
  secret_key = "7hljoEomUg00rnFeYxLWDq0ZRo6X/H1gi5Bbgxvq"

  # The region you are interested in
  endpoint = "webservices.amazon.com"

  request_uri = "/onca/xml"

  params = {
    "Service" => "AWSECommerceService",
    "Operation" => "ItemSearch",
    "AWSAccessKeyId" => "AKIAIY36EEPI2DZ7GXDQ",
    "AssociateTag" => "project30b-20",
    "SearchIndex" => "All",
    "Keywords" => "#{search_item}",
    "ResponseGroup" => "Images,Small"
  }

  # Set current timestamp if not set
  params["Timestamp"] = Time.now.gmtime.iso8601 if !params.key?("Timestamp")

  # Generate the canonical query
  canonical_query_string = params.sort.collect do |key, value|
    [URI.escape(key.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")), URI.escape(value.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))].join('=')
  end.join('&')

  # Generate the string to be signed
  string_to_sign = "GET\n#{endpoint}\n#{request_uri}\n#{canonical_query_string}"

  # Generate the signature required by the Product Advertising API
  signature = Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest.new('sha256'), secret_key, string_to_sign)).strip()

  # Generate the signed URL
  request_url = "http://#{endpoint}#{request_uri}?#{canonical_query_string}&Signature=#{URI.escape(signature, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))}"

  puts "Signed URL: \"#{request_url}\""

  response = HTTParty.get "#{request_url}"

  @hash_response = Crack::XML.parse(response.to_s)

  puts "HASH_RESPONSE:"
  require('pp')
  pp @hash_response["ItemSearchResponse"]["Items"]["Item"]
  @items_list = @hash_response["ItemSearchResponse"]["Items"]["Item"][0...9]
  render('profile')
  end

end


{"ItemSearchResponse"=>
  {"OperationRequest"=>
    {"HTTPHeaders"=>{"Header"=>{"Name"=>"UserAgent", "Value"=>"Ruby"}},
     "RequestId"=>"ffd01b5f-d63d-42e3-a426-7cec14c408a0",
     "Arguments"=>
      {"Argument"=>
        [{"Name"=>"AWSAccessKeyId", "Value"=>"AKIAIY36EEPI2DZ7GXDQ"},
         {"Name"=>"AssociateTag", "Value"=>"project30b-20"},
         {"Name"=>"Keywords", "Value"=>"socks"},
         {"Name"=>"Operation", "Value"=>"ItemSearch"},
         {"Name"=>"ResponseGroup", "Value"=>"Images,Small"},
         {"Name"=>"SearchIndex", "Value"=>"All"},
         {"Name"=>"Service", "Value"=>"AWSECommerceService"},
         {"Name"=>"Timestamp", "Value"=>"2017-12-07T22:15:42Z"},
         {"Name"=>"Signature",
          "Value"=>"c6JfrfxneFkm6B31/ZVVVjpD9PqYSkJBvPlPnIOh8nM="}]},
     "RequestProcessingTime"=>"0.1627983220000000"},
   "Items"=>
    {"Request"=>
      {"IsValid"=>"True",
       "ItemSearchRequest"=>
        {"Keywords"=>"socks",
         "ResponseGroup"=>["Images", "Small"],
         "SearchIndex"=>"All"}},
     "TotalResults"=>"2489120",
     "TotalPages"=>"248912",
     "MoreSearchResultsUrl"=>
      "https://www.amazon.com/gp/search?linkCode=xm2&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&keywords=socks&tag=project30b-20&creative=386001&url=search-alias%3Daws-amazon-aps&camp=2025",
     "Item"=>
      [{"ASIN"=>"B01N9GO7Y9",
        "ParentASIN"=>"B077T3CVX4",
        "DetailPageURL"=>
         "https://www.amazon.com/Loritta-Womens-Vintage-Winter-Multicolor/dp/B01N9GO7Y9?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01N9GO7Y9",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Loritta-Womens-Vintage-Winter-Multicolor/dp/tech-data/B01N9GO7Y9?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01N9GO7Y9"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B01N9GO7Y9&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01N9GO7Y9"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B01N9GO7Y9&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01N9GO7Y9"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B01N9GO7Y9&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01N9GO7Y9"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B01N9GO7Y9?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01N9GO7Y9"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B01N9GO7Y9?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01N9GO7Y9"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B01N9GO7Y9?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01N9GO7Y9"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL75_.jpg",
          "Height"=>"69",
          "Width"=>"75"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL160_.jpg",
          "Height"=>"147",
          "Width"=>"160"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL.jpg",
          "Height"=>"458",
          "Width"=>"500"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL30_.jpg",
               "Height"=>"27",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL75_.jpg",
               "Height"=>"69",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL75_.jpg",
               "Height"=>"69",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL110_.jpg",
               "Height"=>"101",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL160_.jpg",
               "Height"=>"147",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL.jpg",
               "Height"=>"458",
               "Width"=>"500"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51QoOb1R5XL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51QoOb1R5XL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51QoOb1R5XL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51QoOb1R5XL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51QoOb1R5XL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51QoOb1R5XL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51rXrFwTHPL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51rXrFwTHPL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51rXrFwTHPL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51rXrFwTHPL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51rXrFwTHPL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51rXrFwTHPL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51K%2Bbkcv7fL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"28"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51K%2Bbkcv7fL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"71"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51K%2Bbkcv7fL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"71"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51K%2Bbkcv7fL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"104"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51K%2Bbkcv7fL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"152"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51K%2Bbkcv7fL.jpg",
               "Height"=>"500",
               "Width"=>"475"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61lUP%2BtOsCL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61lUP%2BtOsCL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61lUP%2BtOsCL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61lUP%2BtOsCL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61lUP%2BtOsCL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61lUP%2BtOsCL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SyOH68h4L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SyOH68h4L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SyOH68h4L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SyOH68h4L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SyOH68h4L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SyOH68h4L.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL30_.jpg",
               "Height"=>"27",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL75_.jpg",
               "Height"=>"69",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL75_.jpg",
               "Height"=>"69",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL110_.jpg",
               "Height"=>"101",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL._SL160_.jpg",
               "Height"=>"147",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61S1DNtN4EL.jpg",
               "Height"=>"458",
               "Width"=>"500"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"ProductGroup"=>"Apparel",
          "Title"=>
           "Loritta 5 Pairs Womens Vintage Style Winter Warm Thick Knit Wool Cozy Crew Socks,Free size,Multicolor"}},
       {"ASIN"=>"B004QF0TFQ",
        "ParentASIN"=>"B0748TGQ86",
        "DetailPageURL"=>
         "https://www.amazon.com/Dickies-6-Pair-Dri-Tech-Moisture-Control/dp/B004QF0TFQ?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B004QF0TFQ",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Dickies-6-Pair-Dri-Tech-Moisture-Control/dp/tech-data/B004QF0TFQ?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B004QF0TFQ"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B004QF0TFQ&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B004QF0TFQ"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B004QF0TFQ&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B004QF0TFQ"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B004QF0TFQ&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B004QF0TFQ"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B004QF0TFQ?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B004QF0TFQ"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B004QF0TFQ?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B004QF0TFQ"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B004QF0TFQ?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B004QF0TFQ"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL75_.jpg",
          "Height"=>"75",
          "Width"=>"67"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL160_.jpg",
          "Height"=>"160",
          "Width"=>"142"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL.jpg",
          "Height"=>"500",
          "Width"=>"444"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"27"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"67"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"67"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"98"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"142"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL.jpg",
               "Height"=>"500",
               "Width"=>"444"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"27"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"67"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"67"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"98"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"142"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41X%2BcYzzpRL.jpg",
               "Height"=>"500",
               "Width"=>"444"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"Manufacturer"=>"Dickies - Royce Too",
          "ProductGroup"=>"Apparel",
          "Title"=>
           "Dickies 6-Pair Dri-Tech Moisture Control Crew Socks Black Sock Size:10-13/Shoe Size: 6-12"}},
       {"ASIN"=>"B01MXIE9RT",
        "ParentASIN"=>"B01N3PR9HM",
        "DetailPageURL"=>
         "https://www.amazon.com/Fruit-Loom-Mens-Black-10-13/dp/B01MXIE9RT?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01MXIE9RT",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Fruit-Loom-Mens-Black-10-13/dp/tech-data/B01MXIE9RT?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01MXIE9RT"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B01MXIE9RT&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01MXIE9RT"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B01MXIE9RT&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01MXIE9RT"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B01MXIE9RT&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01MXIE9RT"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B01MXIE9RT?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01MXIE9RT"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B01MXIE9RT?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01MXIE9RT"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B01MXIE9RT?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01MXIE9RT"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL75_.jpg",
          "Height"=>"75",
          "Width"=>"59"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL160_.jpg",
          "Height"=>"160",
          "Width"=>"126"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL.jpg",
          "Height"=>"500",
          "Width"=>"395"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"24"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"59"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"59"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"87"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"126"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL.jpg",
               "Height"=>"500",
               "Width"=>"395"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"24"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"59"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"59"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"87"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"126"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51GU9CqoIQL.jpg",
               "Height"=>"500",
               "Width"=>"395"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"Manufacturer"=>"Fruit of the Loom Men's Socks",
          "ProductGroup"=>"Apparel",
          "Title"=>
           "Fruit of the Loom Men's Crew 6 Pack Sock, Black, Shoe Size 6-12/Sock Size 10-13"}},
       {"ASIN"=>"B01NBRBPQV",
        "ParentASIN"=>"B01B8DPXAE",
        "DetailPageURL"=>
         "https://www.amazon.com/Tipi-Toe-Colorful-Patterned-size9-11/dp/B01NBRBPQV?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01NBRBPQV",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Tipi-Toe-Colorful-Patterned-size9-11/dp/tech-data/B01NBRBPQV?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBRBPQV"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B01NBRBPQV&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBRBPQV"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B01NBRBPQV&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBRBPQV"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B01NBRBPQV&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBRBPQV"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B01NBRBPQV?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBRBPQV"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B01NBRBPQV?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBRBPQV"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B01NBRBPQV?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBRBPQV"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL._SL75_.jpg",
          "Height"=>"75",
          "Width"=>"56"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL._SL160_.jpg",
          "Height"=>"160",
          "Width"=>"119"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL.jpg",
          "Height"=>"500",
          "Width"=>"372"},
        "ImageSets"=>
         {"ImageSet"=>
           {"SwatchImage"=>
             {"URL"=>
               "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL._SL30_.jpg",
              "Height"=>"30",
              "Width"=>"22"},
            "SmallImage"=>
             {"URL"=>
               "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL._SL75_.jpg",
              "Height"=>"75",
              "Width"=>"56"},
            "ThumbnailImage"=>
             {"URL"=>
               "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL._SL75_.jpg",
              "Height"=>"75",
              "Width"=>"56"},
            "TinyImage"=>
             {"URL"=>
               "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL._SL110_.jpg",
              "Height"=>"110",
              "Width"=>"82"},
            "MediumImage"=>
             {"URL"=>
               "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL._SL160_.jpg",
              "Height"=>"160",
              "Width"=>"119"},
            "LargeImage"=>
             {"URL"=>
               "https://images-na.ssl-images-amazon.com/images/I/51zoI3KVgRL.jpg",
              "Height"=>"500",
              "Width"=>"372"},
            "Category"=>"primary"}},
        "ItemAttributes"=>
         {"ProductGroup"=>"Apparel",
          "Title"=>
           "Tipi Toe Women's 20 Pairs Colorful Patterned Low Cut / No Show Socks, (sock size9-11) Fits shoe size 6-12, WL07-AB"}},
       {"ASIN"=>"B01M0WBQQ5",
        "ParentASIN"=>"B01M5KXCV2",
        "DetailPageURL"=>
         "https://www.amazon.com/Loritta-Womens-Vintage-Winter-Multicolor/dp/B01M0WBQQ5?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01M0WBQQ5",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Loritta-Womens-Vintage-Winter-Multicolor/dp/tech-data/B01M0WBQQ5?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01M0WBQQ5"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B01M0WBQQ5&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01M0WBQQ5"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B01M0WBQQ5&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01M0WBQQ5"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B01M0WBQQ5&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01M0WBQQ5"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B01M0WBQQ5?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01M0WBQQ5"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B01M0WBQQ5?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01M0WBQQ5"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B01M0WBQQ5?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01M0WBQQ5"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL75_.jpg",
          "Height"=>"72",
          "Width"=>"75"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL160_.jpg",
          "Height"=>"153",
          "Width"=>"160"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL.jpg",
          "Height"=>"477",
          "Width"=>"500"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL30_.jpg",
               "Height"=>"29",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL75_.jpg",
               "Height"=>"72",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL75_.jpg",
               "Height"=>"72",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL110_.jpg",
               "Height"=>"105",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL160_.jpg",
               "Height"=>"153",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL.jpg",
               "Height"=>"477",
               "Width"=>"500"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61H3-oimOzL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61H3-oimOzL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61H3-oimOzL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61H3-oimOzL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61H3-oimOzL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61H3-oimOzL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51fZ5A9FCeL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51fZ5A9FCeL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51fZ5A9FCeL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51fZ5A9FCeL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51fZ5A9FCeL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51fZ5A9FCeL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41nAuDntR1L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41nAuDntR1L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41nAuDntR1L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41nAuDntR1L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41nAuDntR1L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41nAuDntR1L.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61C8%2Bbli2OL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61C8%2Bbli2OL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61C8%2Bbli2OL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61C8%2Bbli2OL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61C8%2Bbli2OL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61C8%2Bbli2OL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61VkyX2IbjL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61VkyX2IbjL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61VkyX2IbjL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61VkyX2IbjL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61VkyX2IbjL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61VkyX2IbjL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL30_.jpg",
               "Height"=>"29",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL75_.jpg",
               "Height"=>"72",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL75_.jpg",
               "Height"=>"72",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL110_.jpg",
               "Height"=>"105",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL._SL160_.jpg",
               "Height"=>"153",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hHdSjuEnL.jpg",
               "Height"=>"477",
               "Width"=>"500"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"ProductGroup"=>"Apparel",
          "Title"=>
           "Loritta 5 Pairs Womens Vintage Style Winter Warm Thick Knit Wool Cozy Crew Socks,Free size,Multicolor"}},
       {"ASIN"=>"B071R1XTGX",
        "ParentASIN"=>"B00574M4SK",
        "DetailPageURL"=>
         "https://www.amazon.com/Champion-Double-Performance-No-Show-6-Pack_White_10-13/dp/B071R1XTGX?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B071R1XTGX",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Champion-Double-Performance-No-Show-6-Pack_White_10-13/dp/tech-data/B071R1XTGX?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B071R1XTGX"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B071R1XTGX&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B071R1XTGX"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B071R1XTGX&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B071R1XTGX"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B071R1XTGX&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B071R1XTGX"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B071R1XTGX?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B071R1XTGX"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B071R1XTGX?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B071R1XTGX"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B071R1XTGX?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B071R1XTGX"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL75_.jpg",
          "Height"=>"75",
          "Width"=>"75"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL160_.jpg",
          "Height"=>"160",
          "Width"=>"160"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL.jpg",
          "Height"=>"500",
          "Width"=>"500"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/31ypv-GqkoL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"ProductGroup"=>"Apparel",
          "Title"=>
           "Champion Double Dry Performance Men's No-Show Socks 6-Pack_White_10-13"}},
       {"ASIN"=>"B01NBA0VDI",
        "ParentASIN"=>"B074XCF67W",
        "DetailPageURL"=>
         "https://www.amazon.com/Womens-Animal-Painting-Socks-Cotton/dp/B01NBA0VDI?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01NBA0VDI",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Womens-Animal-Painting-Socks-Cotton/dp/tech-data/B01NBA0VDI?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBA0VDI"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B01NBA0VDI&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBA0VDI"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B01NBA0VDI&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBA0VDI"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B01NBA0VDI&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBA0VDI"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B01NBA0VDI?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBA0VDI"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B01NBA0VDI?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBA0VDI"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B01NBA0VDI?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B01NBA0VDI"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL._SL75_.jpg",
          "Height"=>"74",
          "Width"=>"75"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL._SL160_.jpg",
          "Height"=>"158",
          "Width"=>"160"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL.jpg",
          "Height"=>"494",
          "Width"=>"500"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41zLaWXxVZL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41zLaWXxVZL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41zLaWXxVZL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41zLaWXxVZL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41zLaWXxVZL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/41zLaWXxVZL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61W16bqSkSL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61W16bqSkSL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61W16bqSkSL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61W16bqSkSL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61W16bqSkSL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61W16bqSkSL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51IU2J7ROQL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51IU2J7ROQL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51IU2J7ROQL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51IU2J7ROQL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51IU2J7ROQL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51IU2J7ROQL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61paxCHKO1L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61paxCHKO1L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61paxCHKO1L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61paxCHKO1L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61paxCHKO1L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61paxCHKO1L.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H13gsGzkL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL._SL75_.jpg",
               "Height"=>"74",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL._SL75_.jpg",
               "Height"=>"74",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL._SL110_.jpg",
               "Height"=>"109",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL._SL160_.jpg",
               "Height"=>"158",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51KmAO6VeyL.jpg",
               "Height"=>"494",
               "Width"=>"500"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"ProductGroup"=>"Apparel",
          "Title"=>
           "Womens Cute Animal Painting Socks, Funny and Cool 100% Cotton Art Dog Socks for Women,(5 Pack) Mix Color 5,One Size"}},
       {"ASIN"=>"B010RWD4GM",
        "ParentASIN"=>"B06Y4CJVQY",
        "DetailPageURL"=>
         "https://www.amazon.com/NIKE-Performance-Cushion-Socks-Pairs/dp/B010RWD4GM?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B010RWD4GM",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/NIKE-Performance-Cushion-Socks-Pairs/dp/tech-data/B010RWD4GM?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B010RWD4GM"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B010RWD4GM&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B010RWD4GM"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B010RWD4GM&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B010RWD4GM"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B010RWD4GM&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B010RWD4GM"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B010RWD4GM?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B010RWD4GM"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B010RWD4GM?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B010RWD4GM"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B010RWD4GM?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B010RWD4GM"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL75_.jpg",
          "Height"=>"75",
          "Width"=>"74"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL160_.jpg",
          "Height"=>"160",
          "Width"=>"158"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L.jpg",
          "Height"=>"500",
          "Width"=>"495"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"74"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"74"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"109"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"158"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L.jpg",
               "Height"=>"500",
               "Width"=>"495"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"74"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"74"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"109"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"158"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51lrUC61r6L.jpg",
               "Height"=>"500",
               "Width"=>"495"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"Creator"=>"NIKE",
          "Manufacturer"=>"Nike Equipment (Sporting Goods)",
          "ProductGroup"=>"Sports",
          "Title"=>
           "NIKE Performance Cushion Crew Socks With Band (6 Pairs), Black/White, Large"}},
       {"ASIN"=>"B075D9G69J",
        "DetailPageURL"=>
         "https://www.amazon.com/Zxsales-5Pack-Womens-Vintage-Winter/dp/B075D9G69J?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B075D9G69J",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Zxsales-5Pack-Womens-Vintage-Winter/dp/tech-data/B075D9G69J?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B075D9G69J"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B075D9G69J&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B075D9G69J"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B075D9G69J&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B075D9G69J"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B075D9G69J&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B075D9G69J"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B075D9G69J?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B075D9G69J"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B075D9G69J?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B075D9G69J"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B075D9G69J?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B075D9G69J"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/619ennddslL._SL75_.jpg",
          "Height"=>"75",
          "Width"=>"75"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/619ennddslL._SL160_.jpg",
          "Height"=>"160",
          "Width"=>"160"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/619ennddslL.jpg",
          "Height"=>"500",
          "Width"=>"500"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H-pIDyo6L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H-pIDyo6L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H-pIDyo6L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H-pIDyo6L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H-pIDyo6L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51H-pIDyo6L.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51XOa-TBRjL._SL30_.jpg",
               "Height"=>"22",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51XOa-TBRjL._SL75_.jpg",
               "Height"=>"56",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51XOa-TBRjL._SL75_.jpg",
               "Height"=>"56",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51XOa-TBRjL._SL110_.jpg",
               "Height"=>"82",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51XOa-TBRjL._SL160_.jpg",
               "Height"=>"120",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51XOa-TBRjL.jpg",
               "Height"=>"375",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51aE6Y%2BZ7zL._SL30_.jpg",
               "Height"=>"22",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51aE6Y%2BZ7zL._SL75_.jpg",
               "Height"=>"56",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51aE6Y%2BZ7zL._SL75_.jpg",
               "Height"=>"56",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51aE6Y%2BZ7zL._SL110_.jpg",
               "Height"=>"82",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51aE6Y%2BZ7zL._SL160_.jpg",
               "Height"=>"120",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51aE6Y%2BZ7zL.jpg",
               "Height"=>"375",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61a5mZCttjL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61a5mZCttjL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61a5mZCttjL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61a5mZCttjL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61a5mZCttjL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61a5mZCttjL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61uLec3UHyL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61uLec3UHyL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61uLec3UHyL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61uLec3UHyL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61uLec3UHyL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61uLec3UHyL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61BvlLrnt-L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61BvlLrnt-L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61BvlLrnt-L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61BvlLrnt-L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61BvlLrnt-L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61BvlLrnt-L.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/615%2B7IOD-5L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/615%2B7IOD-5L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/615%2B7IOD-5L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/615%2B7IOD-5L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/615%2B7IOD-5L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/615%2B7IOD-5L.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61ufVgADYFL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61ufVgADYFL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61ufVgADYFL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61ufVgADYFL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61ufVgADYFL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61ufVgADYFL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/619ennddslL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/619ennddslL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/619ennddslL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/619ennddslL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/619ennddslL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/619ennddslL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"ProductGroup"=>"Apparel",
          "Title"=>
           "Zxsales 5Pack Womens Vintage Winter Soft Warm Thick Cold Knit Wool Crew Socks"}},
       {"ASIN"=>"B06Y1WCPL4",
        "ParentASIN"=>"B01N90FE6I",
        "DetailPageURL"=>
         "https://www.amazon.com/Chalier-Womens-Famous-Painting-Printed/dp/B06Y1WCPL4?psc=1&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B06Y1WCPL4",
        "ItemLinks"=>
         {"ItemLink"=>
           [{"Description"=>"Technical Details",
             "URL"=>
              "https://www.amazon.com/Chalier-Womens-Famous-Painting-Printed/dp/tech-data/B06Y1WCPL4?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B06Y1WCPL4"},
            {"Description"=>"Add To Baby Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/baby/add-item.html?asin.0=B06Y1WCPL4&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B06Y1WCPL4"},
            {"Description"=>"Add To Wedding Registry",
             "URL"=>
              "https://www.amazon.com/gp/registry/wedding/add-item.html?asin.0=B06Y1WCPL4&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B06Y1WCPL4"},
            {"Description"=>"Add To Wishlist",
             "URL"=>
              "https://www.amazon.com/gp/registry/wishlist/add-item.html?asin.0=B06Y1WCPL4&SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B06Y1WCPL4"},
            {"Description"=>"Tell A Friend",
             "URL"=>
              "https://www.amazon.com/gp/pdp/taf/B06Y1WCPL4?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B06Y1WCPL4"},
            {"Description"=>"All Customer Reviews",
             "URL"=>
              "https://www.amazon.com/review/product/B06Y1WCPL4?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B06Y1WCPL4"},
            {"Description"=>"All Offers",
             "URL"=>
              "https://www.amazon.com/gp/offer-listing/B06Y1WCPL4?SubscriptionId=AKIAIY36EEPI2DZ7GXDQ&tag=project30b-20&linkCode=xm2&camp=2025&creative=386001&creativeASIN=B06Y1WCPL4"}]},
        "SmallImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL75_.jpg",
          "Height"=>"65",
          "Width"=>"75"},
        "MediumImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL160_.jpg",
          "Height"=>"140",
          "Width"=>"160"},
        "LargeImage"=>
         {"URL"=>
           "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL.jpg",
          "Height"=>"436",
          "Width"=>"500"},
        "ImageSets"=>
         {"ImageSet"=>
           [{"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL30_.jpg",
               "Height"=>"26",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL75_.jpg",
               "Height"=>"65",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL75_.jpg",
               "Height"=>"65",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL110_.jpg",
               "Height"=>"96",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL160_.jpg",
               "Height"=>"140",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL.jpg",
               "Height"=>"436",
               "Width"=>"500"},
             "Category"=>"swatch"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51qekceYOeL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51qekceYOeL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51qekceYOeL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51qekceYOeL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51qekceYOeL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51qekceYOeL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51SCKU9T-TL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51SCKU9T-TL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51SCKU9T-TL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51SCKU9T-TL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51SCKU9T-TL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51SCKU9T-TL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hanFxs72L._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hanFxs72L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hanFxs72L._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hanFxs72L._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hanFxs72L._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61hanFxs72L.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61sli4-FfwL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61sli4-FfwL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61sli4-FfwL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61sli4-FfwL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61sli4-FfwL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61sli4-FfwL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SttzmkRTL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SttzmkRTL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SttzmkRTL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SttzmkRTL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SttzmkRTL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/61SttzmkRTL.jpg",
               "Height"=>"500",
               "Width"=>"500"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/6147W4uiHoL._SL30_.jpg",
               "Height"=>"30",
               "Width"=>"26"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/6147W4uiHoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"64"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/6147W4uiHoL._SL75_.jpg",
               "Height"=>"75",
               "Width"=>"64"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/6147W4uiHoL._SL110_.jpg",
               "Height"=>"110",
               "Width"=>"94"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/6147W4uiHoL._SL160_.jpg",
               "Height"=>"160",
               "Width"=>"137"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/6147W4uiHoL.jpg",
               "Height"=>"500",
               "Width"=>"429"},
             "Category"=>"variant"},
            {"SwatchImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL30_.jpg",
               "Height"=>"26",
               "Width"=>"30"},
             "SmallImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL75_.jpg",
               "Height"=>"65",
               "Width"=>"75"},
             "ThumbnailImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL75_.jpg",
               "Height"=>"65",
               "Width"=>"75"},
             "TinyImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL110_.jpg",
               "Height"=>"96",
               "Width"=>"110"},
             "MediumImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL._SL160_.jpg",
               "Height"=>"140",
               "Width"=>"160"},
             "LargeImage"=>
              {"URL"=>
                "https://images-na.ssl-images-amazon.com/images/I/51M31w6zYnL.jpg",
               "Height"=>"436",
               "Width"=>"500"},
             "Category"=>"primary"}]},
        "ItemAttributes"=>
         {"ProductGroup"=>"Apparel",
          "Title"=>
           "Chalier 4 Pairs Womens Famous Painting Art Printed Funny Casual Cotton Crew Socks,Free size"}}]},
   "xmlns"=>"http://webservices.amazon.com/AWSECommerceService/2011-08-01"}}
